// <auto-generated />
using FindMyRoom.DataService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FindMyRoom.DataService.Migrations
{
    [DbContext(typeof(FindMyRoomDb))]
    [Migration("20190317121320_RoomTypeAdded")]
    partial class RoomTypeAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FindMyRoom.Entities.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost");

                    b.Property<int>("RenterId");

                    b.Property<int>("RoomId");

                    b.Property<string>("Status");

                    b.HasKey("BookId");

                    b.HasIndex("RenterId");

                    b.HasIndex("RoomId");

                    b.ToTable("FMRBookingList");
                });

            modelBuilder.Entity("FindMyRoom.Entities.Models.Owner", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PartnerId");

                    b.Property<int>("RoomId");

                    b.HasKey("OwnerID");

                    b.HasIndex("PartnerId");

                    b.HasIndex("RoomId");

                    b.ToTable("FMROwners");
                });

            modelBuilder.Entity("FindMyRoom.Entities.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Area")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<int>("Cost");

                    b.Property<string>("Description");

                    b.Property<string>("Furniture");

                    b.Property<int>("NoOfBeds");

                    b.Property<int>("Pincode");

                    b.Property<string>("RoomType");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("RoomId");

                    b.ToTable("FMRRooms");
                });

            modelBuilder.Entity("FindMyRoom.Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserAddress")
                        .IsRequired();

                    b.Property<string>("UserEmail")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPassword")
                        .IsRequired();

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired();

                    b.Property<string>("UserStatus");

                    b.Property<string>("UserType");

                    b.HasKey("UserId");

                    b.ToTable("FMRUsers");
                });

            modelBuilder.Entity("FindMyRoom.Entities.Models.WishList", b =>
                {
                    b.Property<int>("WishListId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RenterId");

                    b.Property<int>("RoomId");

                    b.HasKey("WishListId");

                    b.HasIndex("RenterId");

                    b.HasIndex("RoomId");

                    b.ToTable("FMRWishLists");
                });

            modelBuilder.Entity("FindMyRoom.Entities.Models.Book", b =>
                {
                    b.HasOne("FindMyRoom.Entities.Models.User", "FMRUsers")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FindMyRoom.Entities.Models.Room", "FMRRooms")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FindMyRoom.Entities.Models.Owner", b =>
                {
                    b.HasOne("FindMyRoom.Entities.Models.User", "FMRUsers")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FindMyRoom.Entities.Models.Room", "FMRRooms")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FindMyRoom.Entities.Models.WishList", b =>
                {
                    b.HasOne("FindMyRoom.Entities.Models.User", "FMRUsers")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FindMyRoom.Entities.Models.Room", "FMRRooms")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
